// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZly-FnQGOGe6-iy3htaqT5oE7GRuJAM0',
    appId: '1:89991785385:web:997bd9be695f5993ebb2b8',
    messagingSenderId: '89991785385',
    projectId: 'instgram-181b5',
    authDomain: 'instgram-181b5.firebaseapp.com',
    storageBucket: 'instgram-181b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3RshDjJ79tIhmpw2x05-oUTFHauVzyc',
    appId: '1:89991785385:android:fe4d9d4532f05b3bebb2b8',
    messagingSenderId: '89991785385',
    projectId: 'instgram-181b5',
    storageBucket: 'instgram-181b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_xunG4-QMIqYnnlBXxVV5vkJCIF2kCnI',
    appId: '1:89991785385:ios:7fcb658c71ea1871ebb2b8',
    messagingSenderId: '89991785385',
    projectId: 'instgram-181b5',
    storageBucket: 'instgram-181b5.firebasestorage.app',
    iosBundleId: 'com.example.level4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_xunG4-QMIqYnnlBXxVV5vkJCIF2kCnI',
    appId: '1:89991785385:ios:7fcb658c71ea1871ebb2b8',
    messagingSenderId: '89991785385',
    projectId: 'instgram-181b5',
    storageBucket: 'instgram-181b5.firebasestorage.app',
    iosBundleId: 'com.example.level4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZly-FnQGOGe6-iy3htaqT5oE7GRuJAM0',
    appId: '1:89991785385:web:a48db8b1a1d499beebb2b8',
    messagingSenderId: '89991785385',
    projectId: 'instgram-181b5',
    authDomain: 'instgram-181b5.firebaseapp.com',
    storageBucket: 'instgram-181b5.firebasestorage.app',
  );
}
